import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { poppins } from './ui/fonts';
import './globals.css'
import { Analytics } from '@vercel/analytics/react';
import Navbar from './components/Navbar';
import LeftNavbar from './components/Left-Nav';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <LeftNavbar />
        {children}
              <Analytics />
</body>
    </html>
  )
}
