import type { Metadata } from 'next'
import { poppins } from './ui/fonts';
import './globals.css'
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import Navbar from './lib/Navbar';
import LeftNavbar from './lib/Left-Nav';
import {PagesProvider, ThemeProvider} from './context';
import ThemedDiv from './utils/ThemedDiv';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
{``}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">        

      <body className={`${poppins.className} flex`}>
      <ThemeProvider>
        <PagesProvider>

      <LeftNavbar />

       <div className='flex flex-col w-full'>

          <Navbar />
         
        <ThemedDiv>{/*  I used a component
          because when i used div here 
          dark/light theme wouldn't apply to all of the page. */}
        {children}
        </ThemedDiv>
       </div>
       </PagesProvider>

    </ThemeProvider>
    <SpeedInsights />
   <Analytics />
</body>
    </html>
  )
}
