import type { Metadata } from 'next'
import { poppins } from './ui/fonts';
import './globals.css'
import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import Navbar from './lib/Navbar';
import LeftNavbar from './lib/Left-Nav';
import {PagesProvider} from './context';
import { cookies } from 'next/headers';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
{``}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
const cookieStore = cookies();
const theme = cookieStore.get('theme')?.value;
  return (
    <html lang="en">        
      <body 
      className={`${poppins.className} ${theme==='light' ? ' bg-white' : 'bg-slate-700 text-slate-100'}
      flex dark:bg-slate-700 dark:text-stone-100`}>
        <PagesProvider>
          <LeftNavbar />
          <div className='flex flex-col w-full'>
          <Navbar />
            {children}
          </div>
        </PagesProvider>
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  )
}
